language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - APPLICATION_ENV="testing" DB_USERNAME="root"

before_install:
  - mysql -u$DB_USERNAME -e 'create database bazalt_cms;'
  - mysql -u$DB_USERNAME bazalt_cms < install.sql
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('awdawd') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p tmp/logs
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
